<?php

namespace Database\Seeders;

use App\Models\Warga;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //sebagai contoh user yang digunakan untuk login
        $data=[
        // [  
        //     'nik' => '111111',
        //     'nama' => 'Sukijan',
        //     'password' => '123456',
        //     'level' => 'RW',
        //     'jenis_kelamin' => 'Laki-laki',
        //     'tanggal_lahir' => '1990-01-01',
        //     'alamat' => 'paiton',
        //     'no_telepon' => '081234567890',
        //     'agama' => 'Islam',
        //     'statusKawin' => 'kawin',
        //     'pekerjaan' => 'Wiraswasta',
        //     'no_rt' => '3',
        //     'id_keluarga' => null, // ID Keluarga yang terkait
        // ],
        // [
        //     'nik' => '222222',
        //     'nama' => 'Soebandi',
        //     'password' => '123456',
        //     'level' => 'RT',
        //     'jenis_kelamin' => 'Laki-laki',
        //     'tanggal_lahir' => '1990-01-01',
        //     'alamat' => 'paiton',
        //     'no_telepon' => '081234567890',
        //     'agama' => 'Islam',
        //     'statusKawin' => 'kawin',
        //     'pekerjaan' => 'Guru',
        //     'no_rt' => '3',
        //     'id_keluarga' => null, // ID Keluarga yang terkait
        // ],
        // [
        //     'nik' => '333333',
        //     'nama' => 'Bimantara',
        //     'password' => '123456',
        //     'level' => 'warga',
        //     'jenis_kelamin' => 'Laki-laki',
        //     'tanggal_lahir' => '1990-01-01',
        //     'alamat' => 'paiton',
        //     'no_telepon' => '081234567890',
        //     'agama' => 'Islam',
        //     'statusKawin' => 'Belum kawin',
        //     'pekerjaan' => 'Mahasiswa',
        //     'no_rt' => '3',
        //     'id_keluarga' => null, // ID Keluarga yang terkait
        // ],
        [
            'nik' => '3525025606910001',
            'nama' => 'ERNAWATI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1990-05-07',
            'alamat' => 'Jl. Sidoagung no. 1',
            'no_telepon' => '081234987123',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020706170003 ', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525104701120002',
            'nama' => 'FARADISA AZZAHRA AKAYLA PUTRI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2016-09-07',
            'alamat' => 'Jl. Sidoagung no. 1',
            'no_telepon' => '081456789123',
            'agama' => 'Islam',
            'statusKawin' => 'Belum kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020706170003 ', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525021504770003',
            'nama' => 'SUTO',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1970-08-05',
            'alamat' => 'Jl. Sidoagung no. 2',
            'no_telepon' => '089092929374',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525021911089185', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525026801820002',
            'nama' => 'NUR AINI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1971-08-05',
            'alamat' => 'Jl. Sidoagung no. 2',
            'no_telepon' => '089092929999',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525021911089185', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525021104020001',
            'nama' => 'WILLIYANS GINASTIAR',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2006-08-05',
            'alamat' => 'Jl. Sidoagung no. 2',
            'no_telepon' => '087123929374',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525021911089185', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525022107760001',
            'nama' => 'SUKIYANTO',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1975-05-01',
            'alamat' => 'Jl. Sidoagung no. 3',
            'no_telepon' => '089876543123',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525025608810003',
            'nama' => 'UMI KULSUM',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1979-01-01',
            'alamat' => 'Jl. Sidoagung no. 3',
            'no_telepon' => '088876543777',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525020606010002',
            'nama' => 'YUSUF EFENDI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1990-06-01',
            'alamat' => 'Jl. Sidoagung no. 3',
            'no_telepon' => '088876543543',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525022906070002',
            'nama' => 'YUSUF ANDRE SETIAWAN',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2004-08-08',
            'alamat' => 'Jl. Sidoagung no. 3',
            'no_telepon' => '089776543543',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525022703850021',
            'nama' => 'SUHERI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1990-08-08',
            'alamat' => 'Jl. Sidoagung no. 4',
            'no_telepon' => '089776543123',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020112110002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525024302910002',
            'nama' => 'MARIATI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1991-08-08',
            'alamat' => 'Jl. Sidoagung no. 4',
            'no_telepon' => '087654123892',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'no_rt' => '1',
            'id_keluarga' => '3525020112110002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525020307100001',
            'nama' => 'ANDRIAN PURBA ADI SAPUTRO',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '1995-11-12',
            'alamat' => 'Jl. Sidoagung no. 4',
            'no_telepon' => '087654123544',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020112110002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3524012507870001',
            'nama' => 'MARDI UTOMO',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '2000-12-12',
            'alamat' => 'Jl. Sidoagung no. 5',
            'no_telepon' => '087654123333',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020201150002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525024702870002',
            'nama' => 'SUNARTI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1997-02-05',
            'alamat' => 'Jl. Sidoagung no. 5',
            'no_telepon' => '087654123333',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020201150002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525023005120002',
            'nama' => 'AHMAD IRSYAD AL MAHBUB',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '2016-09-06',
            'alamat' => 'Jl. Sidoagung no. 5',
            'no_telepon' => null,
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020201150002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525027112420014',
            'nama' => 'KASIH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1980-02-05',
            'alamat' => 'Jl. Sidoagung no. 6',
            'no_telepon' => '087657653333',
            'agama' => 'Islam',
            'statusKawin' => 'Cerai Mati',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'no_rt' => '1',
            'id_keluarga' => '3525020202120004', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525020805900001',
            'nama' => 'MUHAMMAD ATIQ',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2003-02-05',
            'alamat' => 'Jl. Sidoagung no. 7',
            'no_telepon' => '089907653434',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525026105900001',
            'nama' => 'SITI MUAWANAH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2005-07-07',
            'alamat' => 'Jl. Sidoagung no. 7',
            'no_telepon' => '089907653999',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525026602150001',
            'nama' => 'PUTRI ABIDA DAMIYA AMBARWATI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2012-07-07',
            'alamat' => 'Jl. Sidoagung no. 7',
            'no_telepon' => null,
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525026905120002',
            'nama' => 'FITRIA MELATI PUTRI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2013-09-09',
            'alamat' => 'Jl. Sidoagung no. 7',
            'no_telepon' => null,
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3524110508780004',
            'nama' => 'HADI SUTONO',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1975-02-05',
            'alamat' => 'Jl. Sidoagung no. 8',
            'no_telepon' => '089907653888',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525025406900002',
            'nama' => 'HANIK PURWATIH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1975-07-11',
            'alamat' => 'Jl. Sidoagung no. 8',
            'no_telepon' => '089876123789',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'no_rt' => '1',
            'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525024103090001',
            'nama' => 'ADINDA AINUR RAHMA',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2001-05-11',
            'alamat' => 'Jl. Sidoagung no. 8',
            'no_telepon' => '089876123111',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525021508130003',
            'nama' => 'ALFIN ROSID AL FUADI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '2009-12-11',
            'alamat' => 'Jl. Sidoagung no. 8',
            'no_telepon' => '089876123654',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525020207790004',
            'nama' => 'DAI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '1979-09-07',
            'alamat' => 'Jl. Sidoagung no. 9',
            'no_telepon' => '082222123654',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525024510820002',
            'nama' => 'ROMLAH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1987-07-02',
            'alamat' => 'Jl. Sidoagung no. 9',
            'no_telepon' => '082222123123',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'no_rt' => '1',
            'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525025704110002',
            'nama' => 'CINTA APRILIA ANGGREANI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2002-07-02',
            'alamat' => 'Jl. Sidoagung no. 9',
            'no_telepon' => '082222123111',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525022007030001',
            'nama' => 'MOHAMMAD ANUGRAH FEBRIAN',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '2011-09-07',
            'alamat' => 'Jl. Sidoagung no. 9',
            'no_telepon' => '089125678222',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525023112750004',
            'nama' => 'SAKRI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-Laki',
            'tanggal_lahir' => '1976-09-11',
            'alamat' => 'Jl. Sidoagung no. 10',
            'no_telepon' => '089125678111',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020312080005', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525026704810022',
            'nama' => 'SOLIKAHTIN',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1980-09-11',
            'alamat' => 'Jl. Sidoagung no. 10',
            'no_telepon' => '088765999111',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020312080005', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525021706020003',
            'nama' => 'ABDUL ROHMAN',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1977-11-11',
            'alamat' => 'Jl. Sidoagung no. 10',
            'no_telepon' => '088765234567',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020312080005', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525021806720001',
            'nama' => 'JUMALI',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1970-12-08',
            'alamat' => 'Jl. Sidoagung no. 11',
            'no_telepon' => '088111234567',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525024303750002',
            'nama' => 'DASIH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1974-08-08',
            'alamat' => 'Jl. Sidoagung no. 11',
            'no_telepon' => '088111234123',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525025007100002',
            'nama' => 'MUTIARA RAHMAH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '2019-08-08',
            'alamat' => 'Jl. Sidoagung no. 11',
            'no_telepon' => null,
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525022109980001',
            'nama' => 'MUHAMMAT ILHAM SAPUTRA',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1999-11-07',
            'alamat' => 'Jl. Sidoagung no. 11',
            'no_telepon' => '088111234344',
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525020208820002',
            'nama' => 'MUSTAQIM',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '1990-12-07',
            'alamat' => 'Jl. Sidoagung no. 12',
            'no_telepon' => '088111231234',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020410160002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3506165410900001',
            'nama' => 'SITI MUNAWAROH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1992-12-07',
            'alamat' => 'Jl. Sidoagung no. 12',
            'no_telepon' => '088111231999',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Wiraswasta',
            'no_rt' => '1',
            'id_keluarga' => '3525020410160002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3506162406110001',
            'nama' => 'MAULANA FAHMI NASRULLOH',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2017-12-07',
            'alamat' => 'Jl. Sidoagung no. 12',
            'no_telepon' => null,
            'agama' => 'Islam',
            'statusKawin' => 'Belum Kawin',
            'pekerjaan' => 'Pelajar',
            'no_rt' => '1',
            'id_keluarga' => '3525020410160002', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525021207750024',
            'nama' => 'SAMSUDIN',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Laki-laki',
            'tanggal_lahir' => '2000-09-11',
            'alamat' => 'Jl. Sidoagung no. 13',
            'no_telepon' => '089765111222',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'PNS',
            'no_rt' => '1',
            'id_keluarga' => '3525020410160003', // ID Keluarga yang terkait
        ],
        [
            'nik' => '3525026504780002',
            'nama' => 'SITI MUSLIKHAH ',
            'password' => '123456',
            'level' => 'warga',
            'jenis_kelamin' => 'Perempuan',
            'tanggal_lahir' => '1999-11-11',
            'alamat' => 'Jl. Sidoagung no. 13',
            'no_telepon' => '089765988112',
            'agama' => 'Islam',
            'statusKawin' => 'Kawin',
            'pekerjaan' => 'Ibu Rumah Tangga',
            'no_rt' => '1',
            'id_keluarga' => '3525020410160003', // ID Keluarga yang terkait
        ],
    ];

        DB::table('warga')->insert($data);
    }
}
