<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //sebagai contoh user yang digunakan untuk login
        $data = [
            [
                'nik' => '111111',
                'nama' => 'Sukijan',
                'password' => '123456',
                'level' => 'RW',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'paiton',
                'no_telepon' => '081234567890',
                'agama' => 'Islam',
                'statusKawin' => 'kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => null, // ID Keluarga yang terkait
            ],
            [
                'nik' => '222222',
                'nama' => 'Soebandi',
                'password' => '123456',
                'level' => 'RT',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'paiton',
                'no_telepon' => '081234567890',
                'agama' => 'Islam',
                'statusKawin' => 'kawin',
                'pekerjaan' => 'Guru',
                'no_rt' => '3',
                'id_keluarga' => null, // ID Keluarga yang terkait
            ],
            [
                'nik' => '333333',
                'nama' => 'Bimantara',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'paiton',
                'no_telepon' => '081234567890',
                'agama' => 'Islam',
                'statusKawin' => 'Belum kawin',
                'pekerjaan' => 'Mahasiswa',
                'no_rt' => '3',
                'id_keluarga' => null, // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025606910001',
                'nama' => 'ERNAWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1990-05-07',
                'alamat' => 'Jl. Sidoagung no. 1',
                'no_telepon' => '081234987123',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020706170003 ', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525104701120002',
                'nama' => 'FARADISA AZZAHRA AKAYLA PUTRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2016-09-07',
                'alamat' => 'Jl. Sidoagung no. 1',
                'no_telepon' => '081456789123',
                'agama' => 'Islam',
                'statusKawin' => 'Belum kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020706170003 ', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021504770003',
                'nama' => 'SUTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1970-08-05',
                'alamat' => 'Jl. Sidoagung no. 2',
                'no_telepon' => '089092929374',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525021911089185', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026801820002',
                'nama' => 'NUR AINI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1971-08-05',
                'alamat' => 'Jl. Sidoagung no. 2',
                'no_telepon' => '089092929999',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525021911089185', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021104020001',
                'nama' => 'WILLIYANS GINASTIAR',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2006-08-05',
                'alamat' => 'Jl. Sidoagung no. 2',
                'no_telepon' => '087123929374',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525021911089185', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022107760001',
                'nama' => 'SUKIYANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1975-05-01',
                'alamat' => 'Jl. Sidoagung no. 3',
                'no_telepon' => '089876543123',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025608810003',
                'nama' => 'UMI KULSUM',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1979-01-01',
                'alamat' => 'Jl. Sidoagung no. 3',
                'no_telepon' => '088876543777',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020606010002',
                'nama' => 'YUSUF EFENDI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-06-01',
                'alamat' => 'Jl. Sidoagung no. 3',
                'no_telepon' => '088876543543',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022906070002',
                'nama' => 'YUSUF ANDRE SETIAWAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2004-08-08',
                'alamat' => 'Jl. Sidoagung no. 3',
                'no_telepon' => '089776543543',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020107100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022703850021',
                'nama' => 'SUHERI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-08-08',
                'alamat' => 'Jl. Sidoagung no. 4',
                'no_telepon' => '089776543123',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020112110002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024302910002',
                'nama' => 'MARIATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1991-08-08',
                'alamat' => 'Jl. Sidoagung no. 4',
                'no_telepon' => '087654123892',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '1',
                'id_keluarga' => '3525020112110002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020307100001',
                'nama' => 'ANDRIAN PURBA ADI SAPUTRO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1995-11-12',
                'alamat' => 'Jl. Sidoagung no. 4',
                'no_telepon' => '087654123544',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020112110002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3524012507870001',
                'nama' => 'MARDI UTOMO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2000-12-12',
                'alamat' => 'Jl. Sidoagung no. 5',
                'no_telepon' => '087654123333',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020201150002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024702870002',
                'nama' => 'SUNARTI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1997-02-05',
                'alamat' => 'Jl. Sidoagung no. 5',
                'no_telepon' => '087654123333',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020201150002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525023005120002',
                'nama' => 'AHMAD IRSYAD AL MAHBUB',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2016-09-06',
                'alamat' => 'Jl. Sidoagung no. 5',
                'no_telepon' => null,
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020201150002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027112420014',
                'nama' => 'KASIH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1980-02-05',
                'alamat' => 'Jl. Sidoagung no. 6',
                'no_telepon' => '087657653333',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '1',
                'id_keluarga' => '3525020202120004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020805900001',
                'nama' => 'MUHAMMAD ATIQ',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2003-02-05',
                'alamat' => 'Jl. Sidoagung no. 7',
                'no_telepon' => '089907653434',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026105900001',
                'nama' => 'SITI MUAWANAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2005-07-07',
                'alamat' => 'Jl. Sidoagung no. 7',
                'no_telepon' => '089907653999',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026602150001',
                'nama' => 'PUTRI ABIDA DAMIYA AMBARWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2012-07-07',
                'alamat' => 'Jl. Sidoagung no. 7',
                'no_telepon' => null,
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026905120002',
                'nama' => 'FITRIA MELATI PUTRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2013-09-09',
                'alamat' => 'Jl. Sidoagung no. 7',
                'no_telepon' => null,
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020207120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3524110508780004',
                'nama' => 'HADI SUTONO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1975-02-05',
                'alamat' => 'Jl. Sidoagung no. 8',
                'no_telepon' => '089907653888',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025406900002',
                'nama' => 'HANIK PURWATIH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1975-07-11',
                'alamat' => 'Jl. Sidoagung no. 8',
                'no_telepon' => '089876123789',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '1',
                'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024103090001',
                'nama' => 'ADINDA AINUR RAHMA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2001-05-11',
                'alamat' => 'Jl. Sidoagung no. 8',
                'no_telepon' => '089876123111',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021508130003',
                'nama' => 'ALFIN ROSID AL FUADI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2009-12-11',
                'alamat' => 'Jl. Sidoagung no. 8',
                'no_telepon' => '089876123654',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020209150001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020207790004',
                'nama' => 'DAI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1979-09-07',
                'alamat' => 'Jl. Sidoagung no. 9',
                'no_telepon' => '082222123654',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024510820002',
                'nama' => 'ROMLAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1987-07-02',
                'alamat' => 'Jl. Sidoagung no. 9',
                'no_telepon' => '082222123123',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '1',
                'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025704110002',
                'nama' => 'CINTA APRILIA ANGGREANI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-07-02',
                'alamat' => 'Jl. Sidoagung no. 9',
                'no_telepon' => '082222123111',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022007030001',
                'nama' => 'MOHAMMAD ANUGRAH FEBRIAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2011-09-07',
                'alamat' => 'Jl. Sidoagung no. 9',
                'no_telepon' => '089125678222',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020304100004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525023112750004',
                'nama' => 'SAKRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1976-09-11',
                'alamat' => 'Jl. Sidoagung no. 10',
                'no_telepon' => '089125678111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020312080005', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026704810022',
                'nama' => 'SOLIKAHTIN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1980-09-11',
                'alamat' => 'Jl. Sidoagung no. 10',
                'no_telepon' => '088765999111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020312080005', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021706020003',
                'nama' => 'ABDUL ROHMAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1977-11-11',
                'alamat' => 'Jl. Sidoagung no. 10',
                'no_telepon' => '088765234567',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020312080005', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021806720001',
                'nama' => 'JUMALI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1970-12-08',
                'alamat' => 'Jl. Sidoagung no. 11',
                'no_telepon' => '088111234567',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024303750002',
                'nama' => 'DASIH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1974-08-08',
                'alamat' => 'Jl. Sidoagung no. 11',
                'no_telepon' => '088111234123',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025007100002',
                'nama' => 'MUTIARA RAHMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2019-08-08',
                'alamat' => 'Jl. Sidoagung no. 11',
                'no_telepon' => null,
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022109980001',
                'nama' => 'MUHAMMAT ILHAM SAPUTRA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1999-11-07',
                'alamat' => 'Jl. Sidoagung no. 11',
                'no_telepon' => '088111234344',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020408090003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020208820002',
                'nama' => 'MUSTAQIM',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-12-07',
                'alamat' => 'Jl. Sidoagung no. 12',
                'no_telepon' => '088111231234',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020410160002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3506165410900001',
                'nama' => 'SITI MUNAWAROH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1992-12-07',
                'alamat' => 'Jl. Sidoagung no. 12',
                'no_telepon' => '088111231999',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '1',
                'id_keluarga' => '3525020410160002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3506162406110001',
                'nama' => 'MAULANA FAHMI NASRULLOH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2017-12-07',
                'alamat' => 'Jl. Sidoagung no. 12',
                'no_telepon' => null,
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '1',
                'id_keluarga' => '3525020410160002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021207750024',
                'nama' => 'SAMSUDIN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2000-09-11',
                'alamat' => 'Jl. Sidoagung no. 13',
                'no_telepon' => '089765111222',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '1',
                'id_keluarga' => '3525020410160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026504780002',
                'nama' => 'SITI MUSLIKHAH ',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1999-11-11',
                'alamat' => 'Jl. Sidoagung no. 13',
                'no_telepon' => '089765988112',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '1',
                'id_keluarga' => '3525020410160003', // ID Keluarga yang terkait
            ],
            //WARGA RW 02
            [
                'nik' => '3525020909000002',
                'nama' => 'ACHMAD YASIN ',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1988-12-11',
                'alamat' => 'Jl. Kertarejasa Gang II no. 1',
                'no_telepon' => '089765988222',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '2',
                'id_keluarga' => '3525020502160001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026009770002',
                'nama' => 'YETI WAHYUNI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1977-12-08',
                'alamat' => 'Jl. Kertarejasa Gang II no. 1',
                'no_telepon' => '087765988222',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '2',
                'id_keluarga' => '3525020502160001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022505130001',
                'nama' => 'MOCHAMMAD KELVIN ERDIANSYAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-01-08',
                'alamat' => 'Jl. Kertarejasa Gang II no. 1',
                'no_telepon' => '087765988123',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '2',
                'id_keluarga' => '3525020502160001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020504010005',
                'nama' => 'MUHAMMAD ASPUJI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1966-07-07',
                'alamat' => 'Jl. Kertarejasa Gang II no. 2',
                'no_telepon' => '087765988333',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '2',
                'id_keluarga' => '3525021701120005', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021804860002',
                'nama' => 'BUDI TRI SUTRISNO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1972-06-06',
                'alamat' => 'Jl. Kertarejasa Gang II no. 3',
                'no_telepon' => '082344566677',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '2',
                'id_keluarga' => '3525021701120008', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025007890002',
                'nama' => 'VIDIYAH ASTUTIK',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1977-09-06',
                'alamat' => 'Jl. Kertarejasa Gang II no. 3',
                'no_telepon' => '082344566111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '2',
                'id_keluarga' => '3525021701120008', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020411080001',
                'nama' => 'AGUNG WICAKSONO ALFAATH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2000-11-06',
                'alamat' => 'Jl. Kertarejasa Gang II no. 3',
                'no_telepon' => '082557766111',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '2',
                'id_keluarga' => '3525021701120008', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024212110003',
                'nama' => 'AURA HIDAYAH KHASANAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2011-12-03',
                'alamat' => 'Jl. Kertarejasa Gang II no. 3',
                'no_telepon' => '082557746467',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '2',
                'id_keluarga' => '3525021701120008', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021405890002',
                'nama' => 'NANANG BUKHORI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1980-12-11',
                'alamat' => 'Jl. Kertarejasa Gang II no. 4',
                'no_telepon' => '082557746467',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '2',
                'id_keluarga' => '3525021807160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026909940003',
                'nama' => 'SUGIATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1983-07-11',
                'alamat' => 'Jl. Kertarejasa Gang II no. 4',
                'no_telepon' => '082999946467',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '2',
                'id_keluarga' => '3525021807160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022406860003',
                'nama' => 'SISWANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1975-12-11',
                'alamat' => 'Jl. Kertarejasa Gang II no. 5',
                'no_telepon' => '082557746123',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '2',
                'id_keluarga' => '3525021812150004 ', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3516167107940002',
                'nama' => 'ARINDA META SARI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1982-06-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 5',
                'no_telepon' => '082999946111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '2',
                'id_keluarga' => '3525021812150004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020510150001',
                'nama' => 'MUHAMMAD DAFFA IBNU HAFIDZ',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2004-05-11',
                'alamat' => 'Jl. Kertarejasa Gang II no. 5',
                'no_telepon' => '082557746276',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '2',
                'id_keluarga' => '3525021812150004 ', // ID Keluarga yang terkait
            ],

            //warga rt 03
            [
                'nik' => '3525020211830001',
                'nama' => 'NUR SAMSI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1966-11-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 6',
                'no_telepon' => '082557741111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100005 ', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024101860005',
                'nama' => 'NUR MAYANTI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1977-12-03',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082512121111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100005 ', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026804090001',
                'nama' => 'APRILIA WIDYAWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2000-12-03',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082512123141',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100005 ', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020108840001',
                'nama' => 'AGUS EKO SUSANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1970-09-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082553331111',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024512880023',
                'nama' => 'NUR HASANAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1972-11-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082553335467',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'PNS',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021708090001',
                'nama' => 'MUHAMMAD MIFTAHUL LUTHFI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1987-08-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082553335111',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525023112550009',
                'nama' => 'SAID SUSANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1988-07-11',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082233999567',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021507880001',
                'nama' => 'MUHAMMAD IHSAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1992-07-09',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082233999121',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525016804880001',
                'nama' => 'KHOLIFAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1999-11-09',
                'alamat' => 'Jl. Kertarejasa Gang II no. 7',
                'no_telepon' => '082233111121',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021905100006', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027006760037',
                'nama' => 'DEWIANA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1988-11-09',
                'alamat' => 'Jl. Kertarejasa Gang II no. 8',
                'no_telepon' => '082233111888',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Hidup',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => '3525021906130003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024610010002',
                'nama' => 'PUTRI NUR SUSANTI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2006-10-10',
                'alamat' => 'Jl. Kertarejasa Gang II no. 8',
                'no_telepon' => '082233111232',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021906130003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020111730004',
                'nama' => 'JUNAEDI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1980-12-10',
                'alamat' => 'Jl. Kertarejasa Gang II no. 9',
                'no_telepon' => '082233111455',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => '3525021911089170', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024705720005',
                'nama' => 'VONY ASTUTIK',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-10-10',
                'alamat' => 'Jl. Kertarejasa Gang II no. 10',
                'no_telepon' => '082233556455',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => '3525021911089170', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020912990001',
                'nama' => 'RAMADHAN EKA SATRIO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2001-08-10',
                'alamat' => 'Jl. Kertarejasa Gang II no. 10',
                'no_telepon' => '082233558989',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => '3525021911089170', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021011020002',
                'nama' => 'RIZKI DWI SYAFAAT',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '2006-08-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 10',
                'no_telepon' => '082233557766',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Pelajar',
                'no_rt' => '3',
                'id_keluarga' => '3525021911089170', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525024301720001',
                'nama' => 'LILIS ISTIQOMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Kertarejasa Gang II no. 11',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '3',
                'id_keluarga' => '3525021911089171', // ID Keluarga yang terkait
            ],
            // RT 4
            [
                'nik' => '3522126512930005',
                'nama' => 'ANIK SEFTIYOWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 1',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020412150003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022312140002',
                'nama' => 'MUHAMAD RENDITYA ADAM AL FATIH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 1',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020412150003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021003820001',
                'nama' => 'SALIM EFFENDI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 2',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020504160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3527054107930273',
                'nama' => 'SAHRIMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 2',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020504160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021202160001',
                'nama' => 'MUHAMMAD ASSYAFAAT',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 2',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020504160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3506152206810002',
                'nama' => 'KUSWANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 3',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020509130002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027112670004',
                'nama' => 'INEM',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 3',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020509130002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026010990001',
                'nama' => 'DEVI OKTASARI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 3',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020509130002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027112670018',
                'nama' => 'KARSI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 4',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020601120010', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022504900002',
                'nama' => 'NUR HADI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 4',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020601120010', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022408940002',
                'nama' => 'MOHAMAD ARIF',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 4',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020601120010', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525162901900002',
                'nama' => 'RIZKI NURDIYANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 5',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020708120004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025208900022',
                'nama' => 'INA ARDIYANTI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 5',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020708120004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025606130001',
                'nama' => 'PUTRI YASMIN NURDIANA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 5',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020708120004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525041206900002',
                'nama' => 'LUQMAN TANTOWI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 6',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020801140001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025512940001',
                'nama' => 'KHUSNUL KHOTIMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 6',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020801140001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022908130002',
                'nama' => 'KMUHAMMAD RIZKY ILHAM SYAPUTRA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 6',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020801140001', // ID Keluarga yang terkait
            ],
            //RT 5
            [
                'nik' => '3525027112710001',
                'nama' => 'PIKAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 7',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020804150004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021807900001',
                'nama' => 'AHMAD SHOLEH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 7',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020804150004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020612000002',
                'nama' => 'ACHMAD ASYARI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 7',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020804150004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021105750001',
                'nama' => 'SARJI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026709840001',
                'nama' => 'SRIANAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026704060001',
                'nama' => 'FIRDA APRILIANA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020203140001',
                'nama' => 'DHARMA YOGA SAPUTRA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027112640012',
                'nama' => 'ALIMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026502790001',
                'nama' => 'SITI MUFLICHAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020206730004',
                'nama' => 'JUADI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021012030001',
                'nama' => 'MUHAMMAD FUAD HASAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022007120001',
                'nama' => 'AHMAD SURURI ROMADLON',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027112580016',
                'nama' => 'HANIFAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 10',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160009', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021404840004',
                'nama' => 'RIANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 11',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020810120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525146909900001',
                'nama' => 'MAULIYANI SEFTY WIDHATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 11',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020810120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025404130002',
                'nama' => 'NAWWARA IZZATUL ISLAM',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 11',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020810120003', // ID Keluarga yang terkait
            ],
            // RT 6
            [
                'nik' => '3525020207880002',
                'nama' => 'NUR HUDA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525045512880002',
                'nama' => 'UMI NASIBAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025508110001',
                'nama' => 'SYAFALIA RAHMADHANIA PUTRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525027005160001',
                'nama' => 'NURRAHMANIA PUTRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020301940001',
                'nama' => 'ACHMAD QOIRUL HIDAYAT',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 13',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020901170005', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525164812940122',
                'nama' => 'SITI ULAIYAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 13',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020901170005', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022204970001',
                'nama' => 'ABDUL ROKHMAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 14',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020906160001', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525020206830001',
                'nama' => 'ABDUL MUCHITH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525044901840001',
                'nama' => 'ZULIATIN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525026702160001',
                'nama' => 'UMMI VARIKHAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021103100002',
                'nama' => 'ACHMAD NAUVAL',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3516011804910001',
                'nama' => 'FALAQI AMNAN ABDULLAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 16',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025006950002',
                'nama' => 'RISKI TAWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 16',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525025601170001',
                'nama' => 'FARIZA KALISTA ADILLAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 16',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160002', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525022607930001',
                'nama' => 'WISNU KIKI SAPUTRO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 17',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3522176103900001',
                'nama' => 'RISNAWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 17',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160003', // ID Keluarga yang terkait
            ],
            [
                'nik' => '3525021904120002',
                'nama' => 'KEVIN APRILLIO RIZKY SAPUTRA',
                'password' => '3525021904120002',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-01-12',
                'alamat' => 'Jl. Onggojoyo No. 17',
                'no_telepon' => '082233551212',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160003', // ID Keluarga yang terkait
            ],
        ];
        DB::table('warga')->insert($data);
    }
}
