<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nik' => '3522126512930005',
                'nama' => 'ANIK SEFTIYOWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1990-01-01',
                'alamat' => 'Jl. Onggojoyo No. 1',
                'no_telepon' => '081234567890',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020412150003',
            ],
            [
                'nik' => '3525022312140002',
                'nama' => 'MUHAMAD RENDITYA ADAM AL FATIH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1990-01-02',
                'alamat' => 'Jl. Onggojoyo No. 1',
                'no_telepon' => '081234567534',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020412150003',
            ],
            [
                'nik' => '3525021003820001',
                'nama' => 'SALIM EFFENDI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1992-05-03',
                'alamat' => 'Jl. Onggojoyo No. 2',
                'no_telepon' => '08123456878',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020504160003',
            ],
            [
                'nik' => '3527054107930273',
                'nama' => 'SAHRIMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1992-07-09',
                'alamat' => 'Jl. Onggojoyo No. 2',
                'no_telepon' => '081234567999',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020504160003',
            ],
            [
                'nik' => '3525021202160001',
                'nama' => 'MUHAMMAD ASSYAFAAT',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-Laki',
                'tanggal_lahir' => '1990-05-15',
                'alamat' => 'Jl. Onggojoyo No. 2',
                'no_telepon' => '081234567890',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pedagang',
                'no_rt' => '4',
                'id_keluarga' => '3525020504160003',
            ],
            [
                'nik' => '3506152206810002',
                'nama' => 'KUSWANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1981-06-22',
                'alamat' => 'Jl. Onggojoyo No. 3',
                'no_telepon' => '081234567891',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Guru/Dosen',
                'no_rt' => '4',
                'id_keluarga' => '3525020509130002 ',
            ],
            [
                'nik' => '3525027112670004',
                'nama' => 'INEM',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1983-12-11',
                'alamat' => 'Jl. Onggojoyo No. 3',
                'no_telepon' => '081234567892',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '4',
                'id_keluarga' => '3525020509130002 ',
            ],
            [
                'nik' => '3525026010990001',
                'nama' => 'DEVI OKTASARI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-10-10',
                'alamat' => 'Jl. Onggojoyo No. 3',
                'no_telepon' => '081234567893',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '4',
                'id_keluarga' => '3525020509130002 ',
            ],
            [
                'nik' => '3525027112670018',
                'nama' => 'KARSI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1967-12-11',
                'alamat' => 'Jl. Onggojoyo No. 4',
                'no_telepon' => '081234567894',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Petani',
                'no_rt' => '4',
                'id_keluarga' => '3525020601120010',
            ],
            [
                'nik' => '3525022504900002',
                'nama' => 'NUR HADI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-04-25',
                'alamat' => 'Jl. Onggojoyo No. 4',
                'no_telepon' => '081234567895',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pedagang',
                'no_rt' => '4',
                'id_keluarga' => '3525020601120010',
            ],
            [
                'nik' => '3525022408940002',
                'nama' => 'MOHAMAD ARIF',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1994-08-24',
                'alamat' => 'Jl. Onggojoyo No. 4',
                'no_telepon' => '081234567896',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020601120010',
            ],
            [
                'nik' => '3525162901900002',
                'nama' => 'RIZKI NURDIYANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-01-29',
                'alamat' => 'Jl. Onggojoyo No. 5',
                'no_telepon' => '081234567897',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Dokter',
                'no_rt' => '4',
                'id_keluarga' => '3525020708120004',
            ],
            [
                'nik' => '3525025208900022',
                'nama' => 'INA ARDIYANTI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1990-08-20',
                'alamat' => 'Jl. Onggojoyo No. 5',
                'no_telepon' => '081234567898',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '4',
                'id_keluarga' => '3525020708120004',
            ],
            [
                'nik' => '3525025606130001',
                'nama' => 'PUTRI YASMIN NURDIANA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-06-15',
                'alamat' => 'Jl. Onggojoyo No. 5',
                'no_telepon' => '081234567899',
                'agama' => 'Islam',
                'statusKawin' => 'Pelajar/Mahasiswa',
                'pekerjaan' => 'Belum Kawin',
                'no_rt' => '4',
                'id_keluarga' => '3525020708120004',
            ],
            [
                'nik' => '3525041206900002',
                'nama' => 'LUQMAN TANTOWI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1980-06-12',
                'alamat' => 'Jl. Onggojoyo No. 6',
                'no_telepon' => '081234567900',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Tentara Nasional Indonesia',
                'no_rt' => '4',
                'id_keluarga' => '3525020801140001',
            ],
            [
                'nik' => '3525025512940001',
                'nama' => 'KHUSNUL KHOTIMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1984-12-15',
                'alamat' => 'Jl. Onggojoyo No. 6',
                'no_telepon' => '081234567901',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '4',
                'id_keluarga' => '3525020801140001',
            ],
            [
                'nik' => '3525022908130002',
                'nama' => 'MUHAMMAD RIZKY ILHAM SYAPUTRA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2003-08-29',
                'alamat' => 'Jl. Onggojoyo No. 6',
                'no_telepon' => '081234567902',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '4',
                'id_keluarga' => '3525020801140001',
            ],
            [
                'nik' => '3525027112710001',
                'nama' => 'PIKAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1971-11-27',
                'alamat' => 'Jl. Onggojoyo No. 7',
                'no_telepon' => '081234567903',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Pedagang',
                'no_rt' => '5',
                'id_keluarga' => '3525020804150004',
            ],
            [
                'nik' => '3525021807900001',
                'nama' => 'AHMAD SHOLEH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1990-07-18',
                'alamat' => 'Jl. Onggojoyo No. 7',
                'no_telepon' => '081234567904',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '5',
                'id_keluarga' => '3525020804150004',
            ],
            [
                'nik' => '3525020612000002',
                'nama' => 'ACHMAD ASYARI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2000-12-06',
                'alamat' => 'Jl. Onggojoyo No. 7',
                'no_telepon' => '081234567905',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '5',
                'id_keluarga' => '3525020804150004',
            ],
            [
                'nik' => '3525021105750001',
                'nama' => 'SARJI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1975-05-11',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '081234567906',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002',
            ],
            [
                'nik' => '3525026709840001',
                'nama' => 'SRIANAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1984-09-06',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '081234567907',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002',
            ],
            [
                'nik' => '3525026704060001',
                'nama' => 'FIRDA APRILIANA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2002-04-06',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '081234567908',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002',
            ],
            [
                'nik' => '3525020203140001',
                'nama' => 'DHARMA YOGA SAPUTRA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2004-03-02',
                'alamat' => 'Jl. Onggojoyo No. 8',
                'no_telepon' => '081234567909',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '5',
                'id_keluarga' => '3525020805090002',
            ],
            [
                'nik' => '3525027112640012',
                'nama' => 'ALIMAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1964-12-11',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '081234567910',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Pedagang',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004',
            ],
            [
                'nik' => '3525026502790001',
                'nama' => 'SITI MUFLICHAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1979-02-25',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '081234567911',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Akuntan',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004',
            ],
            [
                'nik' => '3525020206730004',
                'nama' => 'JUADI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1973-06-02',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '081234567912',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004',
            ],
            [
                'nik' => '3525021012030001',
                'nama' => 'MUHAMMAD FUAD HASAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2001-12-10',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '081234567913',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004',
            ],
            [
                'nik' => '3525022007120001',
                'nama' => 'AHMAD SURURI ROMADLON',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2003-07-20',
                'alamat' => 'Jl. Onggojoyo No. 9',
                'no_telepon' => '081234567914',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160004',
            ],
            [
                'nik' => '3525027112580016',
                'nama' => 'HANIFAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1958-12-25',
                'alamat' => 'Jl. Onggojoyo No. 10',
                'no_telepon' => '081234567915',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Petani',
                'no_rt' => '5',
                'id_keluarga' => '3525020808160009',
            ],
            [
                'nik' => '3525021404840004',
                'nama' => 'RIANTO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1975-04-14',
                'alamat' => 'Jl. Onggojoyo No. 11',
                'no_telepon' => '081234567916',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Kepolisian RI',
                'no_rt' => '5',
                'id_keluarga' => '3525020810120003',
            ],
            [
                'nik' => '3525146909900001',
                'nama' => 'MAULIYANI SEFTY WIDHATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-09-06',
                'alamat' => 'Jl. Onggojoyo No. 11',
                'no_telepon' => '081234567917',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '5',
                'id_keluarga' => '3525020810120003',
            ],
            [
                'nik' => '3525025404130002',
                'nama' => 'NAWWARA IZZATUL ISLAM',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-04-05',
                'alamat' => 'Jl. Onggojoyo No. 11',
                'no_telepon' => '081234567918',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '5',
                'id_keluarga' => '3525020810120003',
            ],
            [
                'nik' => '3525020207880002',
                'nama' => 'NUR HUDA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1978-07-02',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '081234567919',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003',
            ],
            [
                'nik' => '3525045512880002',
                'nama' => 'UMI NASIBAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1981-12-25',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '081234567920',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003',
            ],
            [
                'nik' => '3525025508110001',
                'nama' => 'SYAFALIA RAHMADHANIA PUTRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-08-15',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '081234567921',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003',
            ],
            [
                'nik' => '3525027005160001',
                'nama' => 'NURRAHMANIA PUTRI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2005-05-17',
                'alamat' => 'Jl. Onggojoyo No. 12',
                'no_telepon' => '081234567922',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '6',
                'id_keluarga' => '3525020812100003',
            ],
            [
                'nik' => '3525020301940001',
                'nama' => 'ACHMAD QOIRUL HIDAYAT',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1994-01-03',
                'alamat' => 'Jl. Onggojoyo No. 13',
                'no_telepon' => '081234567923',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020901170005',
            ],
            [
                'nik' => '3525164812940122',
                'nama' => 'SITI ULAIYAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1994-12-14',
                'alamat' => 'Jl. Onggojoyo No. 13',
                'no_telepon' => '081234567924',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Wiraswasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020901170005',
            ],
            [
                'nik' => '3525022204970001',
                'nama' => 'ABDUL ROKHMAN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1957-04-22',
                'alamat' => 'Jl. Onggojoyo No. 14',
                'no_telepon' => '081234567925',
                'agama' => 'Islam',
                'statusKawin' => 'Cerai Mati',
                'pekerjaan' => 'Pensiunan',
                'no_rt' => '6',
                'id_keluarga' => '3525020906160001',
            ],
            [
                'nik' => '3525020206830001',
                'nama' => 'ABDUL MUCHITH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1980-06-02',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '081234567926',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Karyawan Swasta',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003',
            ],
            [
                'nik' => '3525044901840001',
                'nama' => 'ZULIATIN',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1984-01-19',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '081234567927',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003',
            ],
            [
                'nik' => '3525026702160001',
                'nama' => 'UMMI VARIKHAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2003-02-16',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '081234567928',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003',
            ],
            [
                'nik' => '3525021103100002',
                'nama' => 'ACHMAD NAUVAL',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2005-03-10',
                'alamat' => 'Jl. Onggojoyo No. 15',
                'no_telepon' => '081234567929',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '6',
                'id_keluarga' => '3525020910120003',
            ],
            [
                'nik' => '3516011804910001',
                'nama' => 'FALAQI AMNAN ABDULLAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1971-04-18',
                'alamat' => 'Jl. Onggojoyo No. 16',
                'no_telepon' => '081234567930',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160002',
            ],
            [
                'nik' => '3525025006950002',
                'nama' => 'RISKI TAWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1975-06-05',
                'alamat' => 'Jl. Onggojoyo No. 16',
                'no_telepon' => '081234567931',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160002',
            ],
            [
                'nik' => '3525025601170001',
                'nama' => 'FARIZA KALISTA ADILLAH',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1997-01-17',
                'alamat' => 'Jl. Onggojoyo No. 16',
                'no_telepon' => '081234567932',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Kepolisian RI',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160002',
            ],
            [
                'nik' => '3525022607930001',
                'nama' => 'WISNU KIKI SAPUTRO',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '1978-07-26',
                'alamat' => 'Jl. Onggojoyo No. 17',
                'no_telepon' => '081234567933',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pengacara',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160003',
            ],
            [
                'nik' => '3522176103900001',
                'nama' => 'RISNAWATI',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '1980-03-10',
                'alamat' => 'Jl. Onggojoyo No. 17',
                'no_telepon' => '081234567934',
                'agama' => 'Islam',
                'statusKawin' => 'Kawin',
                'pekerjaan' => 'Pegawai Negeri Sipil',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160003',
            ],
            [
                'nik' => '3525021904120002',
                'nama' => 'KEVIN APRILLIO RIZKY SAPUTRA',
                'password' => '123456',
                'level' => 'warga',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2002-04-19',
                'alamat' => 'Jl. Onggojoyo No. 17',
                'no_telepon' => '081234567935',
                'agama' => 'Islam',
                'statusKawin' => 'Belum Kawin',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'no_rt' => '6',
                'id_keluarga' => '3525021006160003',
            ],

        ];

        DB::table('warga')->insert($data);
    }
}
